# Generated by Django 5.2.17 on 2026-08-06 21:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("schools", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ParentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("account_activated", models.BooleanField(default=False)),
                ("phone_verified", models.BooleanField(default=False)),
                ("email_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "student_type",
                    models.CharField(
                        choices=[
                            ("NEW", "New Student"),
                            ("EXISTING", "Existing Student"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "admission_number",
                    models.CharField(editable=False, max_length=40, unique=True),
                ),
                ("surname", models.CharField(max_length=100)),
                ("first_name", models.CharField(max_length=100)),
                ("middle_name", models.CharField(blank=True, max_length=100)),
                (
                    "gender",
                    models.CharField(
                        choices=[("MALE", "Male"), ("FEMALE", "Female")], max_length=10
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "passport",
                    models.ImageField(
                        blank=True, null=True, upload_to="student_passports/"
                    ),
                ),
                ("admission_year", models.PositiveIntegerField()),
                ("exact_admission_date", models.DateField(blank=True, null=True)),
                ("entry_class_name", models.CharField(blank=True, max_length=100)),
                ("previous_school", models.CharField(blank=True, max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("GRADUATED", "Graduated"),
                            ("TRANSFERRED", "Transferred"),
                            ("SUSPENDED", "Suspended"),
                            ("WITHDRAWN", "Withdrawn"),
                        ],
                        default="ACTIVE",
                        max_length=15,
                    ),
                ),
                ("portal_registered_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "current_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="students",
                        to="schools.schoolclass",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentParent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("GUARDIAN", "Guardian"),
                            ("GRANDPARENT", "Grandparent"),
                            ("OTHER", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_primary_contact", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_links",
                        to="students.parentprofile",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="parent_links",
                        to="students.student",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student", "parent"), name="unique_parent_per_student"
                    )
                ],
            },
        ),
    ]
