# Generated by Django 5.2.17 on 2026-08-07 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="department",
            field=models.CharField(
                blank=True,
                choices=[
                    ("SCIENCE", "Science"),
                    ("COMMERCIAL", "Commercial"),
                    ("ARTS", "Arts"),
                ],
                default="",
                max_length=20,
            ),
        ),
    ]
