# Generated by Django 5.1.3 on 2026-08-20 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0002_studentpayment"),
        ("schools", "0008_school_paystack_subaccount_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentpayment",
            name="paystack_subaccount_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="studentpayment",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="student_payments",
                to="schools.school",
            ),
        ),
    ]
