# Generated by Django 5.2.17 on 2026-08-06 21:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=200)),
                ("code", models.CharField(editable=False, max_length=20, unique=True)),
                ("slug", models.SlugField(editable=False, max_length=220, unique=True)),
                ("motto", models.CharField(blank=True, max_length=255)),
                (
                    "logo",
                    models.ImageField(blank=True, null=True, upload_to="school_logos/"),
                ),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("address", models.TextField(blank=True)),
                ("primary_color", models.CharField(default="#0D6EFD", max_length=7)),
                ("secondary_color", models.CharField(default="#FFFFFF", max_length=7)),
                (
                    "subscription_plan",
                    models.CharField(
                        choices=[
                            ("LIFETIME_FREE", "Lifetime Free"),
                            ("BASIC", "Basic"),
                            ("PREMIUM", "Premium"),
                            ("ENTERPRISE", "Enterprise"),
                        ],
                        default="BASIC",
                        max_length=20,
                    ),
                ),
                (
                    "subscription_status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("EXPIRED", "Expired"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                    ),
                ),
                ("subscription_expiry_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="SchoolSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("arm", models.CharField(blank=True, max_length=10)),
                ("order", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="classes",
                        to="schools.schoolsection",
                    ),
                ),
            ],
            options={
                "ordering": ["section__order", "order", "name", "arm"],
            },
        ),
        migrations.CreateModel(
            name="AdmissionNumberCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("admission_year", models.PositiveIntegerField()),
                ("last_number", models.PositiveIntegerField(default=0)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="admission_counters",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("school", "admission_year"),
                        name="unique_admission_counter_per_school_year",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="schoolsection",
            constraint=models.UniqueConstraint(
                fields=("school", "name"), name="unique_section_name_per_school"
            ),
        ),
        migrations.AddConstraint(
            model_name="schoolclass",
            constraint=models.UniqueConstraint(
                fields=("section", "name", "arm"),
                name="unique_class_and_arm_per_section",
            ),
        ),
    ]
