# Generated by Django 5.2.17 on 2026-08-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_teacherclassassignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="schoolsection",
            name="academic_level",
            field=models.CharField(
                choices=[("PRIMARY", "Primary"), ("SECONDARY", "Secondary")],
                default="PRIMARY",
                max_length=20,
            ),
        ),
    ]
