# Generated by Django 5.2.17 on 2026-08-07 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0005_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="subject",
            name="senior_arts",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subject",
            name="senior_commercial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subject",
            name="senior_science",
            field=models.BooleanField(default=False),
        ),
    ]
