# Generated by Django 5.1.3 on 2026-08-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_subject_senior_arts_subject_senior_commercial_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="school_admin_can_manage_fees",
            field=models.BooleanField(
                default=True,
                help_text="Allow this school's admin to create and manage fee structures.",
            ),
        ),
    ]
