# Generated by Django 5.1.3 on 2026-08-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0007_school_school_admin_can_manage_fees"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="paystack_subaccount_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="school",
            name="paystack_subaccount_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="school",
            name="settlement_account_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="school",
            name="settlement_account_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="school",
            name="settlement_bank_code",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="school",
            name="settlement_bank_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
