# Generated by Django 5.1.3 on 2026-08-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0008_school_paystack_subaccount_active_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="portal_service_fee",
            field=models.DecimalField(decimal_places=2, default=400.0, max_digits=10),
        ),
    ]
